@startuml
left to right direction
actor "Administrador" as Admin
actor "Atleta/Delegado" as Atleta
actor "Sistema de Cronometragem" as Crono

rectangle "SGO - Sistema de Gestão das Olimpíadas" {
  usecase "Cadastrar Competição" as UC1
  usecase "Inscrever Atleta" as UC2
  usecase "Alocar Local" as UC3
  usecase "Registrar Resultados" as UC4
  usecase "Gerar Relatório de Medalhas" as UC5
}

Admin --> UC1
Admin --> UC3
Admin --> UC4
Atleta --> UC2
Crono --> UC4
Admin --> UC5
@endum